// Generated by scripts/gen-icons.py from the Material Symbols codepoints file. Do not edit by hand.

/// Material Symbols Sharp glyphs the app uses, addressed by codepoint.
enum MSIconName: UInt32, CaseIterable {
    case arrowBack = 0xe5c4
    case refresh = 0xe5d5
    case settings = 0xe8b8
    case playArrow = 0xe037
    case pause = 0xe034
    case lock = 0xe899
    case check = 0xe668
    case close = 0xe5cd
    case bugReport = 0xe868
    case storefront = 0xea12
    case gesture = 0xe155
    case waterDrop = 0xe798
    case directionsRun = 0xe566
    case chevronRight = 0xe5cc
    case replay = 0xe042
    case skipNext = 0xe044
    case home = 0xe9b2
    case bolt = 0xea0b
    case paid = 0xf041
    case group = 0xea21
    case restartAlt = 0xf053
    case gridOn = 0xe3ec
    case speed = 0xe9e4
    case info = 0xe88e
    case expandMore = 0xe5cf
    case emojiEvents = 0xea23
    case timer = 0xe425
    case warning = 0xf083
    case visibility = 0xe8f4
    case delete = 0xe92e
    case science = 0xea4b
    case touchApp = 0xe913
    case swipe = 0xe9ec
    case trendingUp = 0xe8e5
    case sentimentVeryDissatisfied = 0xe814
    case star = 0xf09a
    case undo = 0xe166
    case flag = 0xf0c6
    case localFireDepartment = 0xef55
    case shield = 0xe9e0
    case add = 0xe145
    case remove = 0xe15b
    case doneAll = 0xe877
    case download = 0xf090

    static let fontName = "MaterialSymbolsSharp-Regular"

    var glyph: String {
        guard let scalar = UnicodeScalar(rawValue) else { return "?" }
        return String(Character(scalar))
    }
}
