#!/usr/bin/env python3
"""Generate Sources/App/MSIconName.swift from the Material Symbols codepoints file.

The app renders icons by Unicode scalar rather than by ligature name, so the
glyph list is pinned here and regenerated when an icon is added. The font's
PostScript name is read from the bundled TTF so Font.custom() gets the exact
name Core Text registers.

Usage: scripts/gen-icons.py [path/to/MaterialSymbolsSharp.codepoints]
"""
from __future__ import annotations

import pathlib
import re
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT = ROOT / "ActualGameplay/Fonts/MaterialSymbolsSharp.ttf"
OUT = ROOT / "ActualGameplay/Sources/App/MSIconName.swift"
DEFAULT_CODEPOINTS = (
    pathlib.Path.home()
    / "Documents/material-design/material-design-icons/variablefont"
    / "MaterialSymbolsSharp[FILL,GRAD,opsz,wght].codepoints"
)

ICONS = [
    "arrow_back", "refresh", "settings", "play_arrow", "pause", "lock", "check", "close",
    "bug_report", "storefront", "gesture", "water_drop", "directions_run", "chevron_right",
    "replay", "skip_next", "home", "bolt", "paid", "group", "restart_alt", "grid_on", "speed",
    "info", "expand_more", "emoji_events", "timer", "warning", "visibility", "delete", "science",
    "touch_app", "swipe", "trending_up", "sentiment_very_dissatisfied", "star", "undo",
    "flag", "local_fire_department", "shield", "add", "remove", "done_all", "download",
]


def postscript_name(path: pathlib.Path) -> str:
    """Name ID 6 from the TTF name table, preferring the Windows (UTF-16BE) record."""
    data = path.read_bytes()
    num_tables = struct.unpack(">H", data[4:6])[0]
    for i in range(num_tables):
        off = 12 + 16 * i
        tag = data[off : off + 4]
        toff = struct.unpack(">I", data[off + 8 : off + 12])[0]
        if tag != b"name":
            continue
        _fmt, count, strings_off = struct.unpack(">HHH", data[toff : toff + 6])
        fallback = None
        for j in range(count):
            rec = toff + 6 + 12 * j
            pid, _eid, _lid, nid, length, so = struct.unpack(">HHHHHH", data[rec : rec + 12])
            if nid != 6:
                continue
            start = toff + strings_off + so
            raw = data[start : start + length]
            if pid == 3:
                return raw.decode("utf-16-be")
            if pid == 1 and fallback is None:
                fallback = raw.decode("mac-roman")
        if fallback:
            return fallback
    raise SystemExit(f"no PostScript name in {path}")


def camel(name: str) -> str:
    return re.sub(r"_(\w)", lambda m: m.group(1).upper(), name)


def main() -> None:
    cp_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CODEPOINTS
    table = {}
    for line in cp_path.read_text().splitlines():
        parts = line.split()
        if len(parts) == 2:
            table[parts[0]] = int(parts[1], 16)
    missing = [n for n in ICONS if n not in table]
    if missing:
        raise SystemExit(f"not in codepoints file: {missing}")
    ps = postscript_name(FONT)
    lines = [
        "// Generated by scripts/gen-icons.py from the Material Symbols codepoints file. Do not edit by hand.",
        "",
        "/// Material Symbols Sharp glyphs the app uses, addressed by codepoint.",
        "enum MSIconName: UInt32, CaseIterable {",
    ]
    for n in ICONS:
        lines.append(f"    case {camel(n)} = 0x{table[n]:04x}")
    lines += [
        "",
        f'    static let fontName = "{ps}"',
        "",
        "    var glyph: String {",
        "        guard let scalar = UnicodeScalar(rawValue) else { return \"?\" }",
        "        return String(Character(scalar))",
        "    }",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(ICONS)} icons, font {ps!r})")


if __name__ == "__main__":
    main()
