import Foundation

/// The three permanent upgrades and what they do to a run. The prices and the shop's odds line
/// come from scripts/economy.py, which plays the runs as arithmetic; rerun it with --write-swift
/// after changing a track, the finale, an effect, or the coin rule.
struct RunnerEconomy: Equatable {
    /// One level of an upgrade: its price, and what it did for the model's reference player (the
    /// better gate and a clean dodge 80% of the time), who buys it just before `run`. `gain` is
    /// the win odds it adds there, in points over the next ten runs; for the coin bonus, coins a win.
    struct Tier: Equatable {
        let cost: Int
        let run: Int
        let gain: Double
    }

    enum Upgrade: String, CaseIterable, Identifiable {
        case startCrowd
        case memberPower
        case coinMultiplier

        var id: String { rawValue }

        var title: String {
            switch self {
            case .startCrowd: return "Starting crowd"
            case .memberPower: return "Member strength"
            case .coinMultiplier: return "Coin bonus"
            }
        }

        var maxLevel: Int { self == .startCrowd ? 20 : 10 }

        /// Entry n is the step from level n to n + 1.
        var tiers: [Tier] {
            switch self {
            case .startCrowd: return RunnerEconomy.startCrowdTiers
            case .memberPower: return RunnerEconomy.memberPowerTiers
            case .coinMultiplier: return RunnerEconomy.coinMultiplierTiers
            }
        }

        func cost(atLevel level: Int) -> Int { tiers[min(max(level, 0), tiers.count - 1)].cost }

        func effectText(atLevel level: Int) -> String {
            switch self {
            case .startCrowd: return "\(RunnerGenerator.baseCrowd + 2 * level) runners"
            case .memberPower: return String(format: "%.2fx damage", 1 + 0.15 * Double(level))
            case .coinMultiplier: return String(format: "%.1fx coins", 1 + 0.2 * Double(level))
            }
        }

        /// What the next level buys, for the shop: "+3% odds at run 12", nil once maxed.
        func previewText(atLevel level: Int) -> String? {
            guard level >= 0, level < maxLevel else { return nil }
            let tier = tiers[level]
            if self == .coinMultiplier {
                return "+\(Int(tier.gain.rounded())) coins a win at run \(tier.run)"
            }
            let points = tier.gain >= 2 ? "\(Int(tier.gain.rounded()))" : String(format: "%.1f", tier.gain)
            return "+\(points)% odds at run \(tier.run)"
        }
    }

    static let base = RunnerEconomy(levels: [:])

    var levels: [String: Int]

    func level(of upgrade: Upgrade) -> Int { levels[upgrade.rawValue] ?? 0 }

    var startCrowd: Int { RunnerGenerator.baseCrowd + 2 * level(of: .startCrowd) }
    var memberPower: Double { 1 + 0.15 * Double(level(of: .memberPower)) }
    var coinMultiplier: Double { 1 + 0.2 * Double(level(of: .coinMultiplier)) }

    /// A three-star win of 0-based run `level` pays this before the coin bonus. It follows the run,
    /// not the crowd: gates multiply a crowd, so paying per survivor made one lucky track worth a
    /// hundred others.
    static func purse(forLevel level: Int) -> Int { 30 + 3 * level }

    /// Share of the purse by stars: a scrappy win pays half, a clean one all of it.
    static let starShare: [Double] = [0, 0.5, 0.75, 1]

    func coins(level: Int, stars: Int) -> Int {
        let share = RunnerEconomy.starShare[min(max(stars, 0), 3)]
        return Int((Double(RunnerEconomy.purse(forLevel: level)) * share * coinMultiplier).rounded())
    }

    // Generated by scripts/economy.py --write-swift. Both odds upgrades cost the same wins of
    // income per point of win odds, a rate that climbs from 5 wins for a typical early purchase to
    // 10 for a late one; a coin level repays itself in 25 to 50 wins.
    // BEGIN TIERS
    static let startCrowdTiers: [Tier] = [
        Tier(cost: 110, run: 5, gain: 2.8),
        Tier(cost: 280, run: 24, gain: 1.2),
        Tier(cost: 300, run: 27, gain: 0.8),
        Tier(cost: 570, run: 47, gain: 1.6),
        Tier(cost: 600, run: 50, gain: 0.9),
        Tier(cost: 1150, run: 70, gain: 2.6),
        Tier(cost: 1200, run: 74, gain: 1.5),
        Tier(cost: 1700, run: 96, gain: 2.0),
        Tier(cost: 1800, run: 100, gain: 1.4),
        Tier(cost: 2450, run: 122, gain: 1.4),
        Tier(cost: 2700, run: 127, gain: 1.3),
        Tier(cost: 3750, run: 151, gain: 0.9),
        Tier(cost: 3950, run: 156, gain: 0.9),
        Tier(cost: 5050, run: 180, gain: 1.1),
        Tier(cost: 5300, run: 186, gain: 1.1),
        Tier(cost: 6050, run: 211, gain: 1.0),
        Tier(cost: 8000, run: 219, gain: 1.6),
        Tier(cost: 8400, run: 246, gain: 0.9),
        Tier(cost: 8800, run: 253, gain: 0.7),
        Tier(cost: 9900, run: 279, gain: 0.7),
    ]
    static let memberPowerTiers: [Tier] = [
        Tier(cost: 500, run: 16, gain: 4.6),
        Tier(cost: 1250, run: 39, gain: 5.1),
        Tier(cost: 2200, run: 61, gain: 5.4),
        Tier(cost: 3550, run: 87, gain: 5.2),
        Tier(cost: 5150, run: 113, gain: 3.6),
        Tier(cost: 7450, run: 141, gain: 3.1),
        Tier(cost: 9900, run: 170, gain: 3.1),
        Tier(cost: 14400, run: 202, gain: 2.3),
        Tier(cost: 20700, run: 236, gain: 2.1),
        Tier(cost: 23200, run: 269, gain: 1.4),
    ]
    static let coinMultiplierTiers: [Tier] = [
        Tier(cost: 340, run: 21, gain: 16.3),
        Tier(cost: 640, run: 43, gain: 25.0),
        Tier(cost: 960, run: 66, gain: 34.3),
        Tier(cost: 1400, run: 91, gain: 41.4),
        Tier(cost: 1850, run: 117, gain: 50.4),
        Tier(cost: 2350, run: 145, gain: 60.8),
        Tier(cost: 2800, run: 174, gain: 70.3),
        Tier(cost: 3800, run: 205, gain: 80.8),
        Tier(cost: 4400, run: 240, gain: 97.5),
        Tier(cost: 5150, run: 273, gain: 106.3),
    ]
    // END TIERS
}
